safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         true
pygments:    false
markdown:    engine
permalink:   /:categories/:title
paginate:    20
#limit_posts: 20

title:         Lambda Mechanic 
description:   One project. One week. No excuses.
base:          http://lambdamechanic.com
author:        Mark Wotton
email:         mwotton@gmail.com

# disqus_id:     disqus
google_analytics:  UA-XXXXXX-1
redirects:   true

exclude:    
- ./tasks
- README.textile

